import { Product } from '@/types';

export const products: Product[] = [
  // --- BANANA CAKES ---
  {
    id: 'bc-classic',
    name: 'Classic Banana Cake',
    description: 'Moist, golden layers of ripe banana and vanilla goodness. Every bite is pure sunshine.',
    price: 3500,
    category: 'banana-cake',
    emoji: '🍌',
    imageId: '1569762404472-026308ba6b64',
    gradientFrom: '#5C1E00',
    gradientTo: '#C27A1A',
    tag: 'Bestseller',
    isAvailable: true,
  },
  {
    id: 'bc-chocolate',
    name: 'Chocolate Chip Banana Cake',
    description: 'Our signature banana cake swirled with rich dark chocolate chips — irresistibly decadent.',
    price: 4000,
    category: 'banana-cake',
    emoji: '🍫',
    imageId: '1606983340126-99ab4feaa64a',
    gradientFrom: '#1A0800',
    gradientTo: '#7C2D12',
    tag: 'Customer Fav',
    isAvailable: true,
  },
  {
    id: 'bc-walnut',
    name: 'Walnut Banana Cake',
    description: 'Nutty roasted walnuts meet soft, warm banana. A texture lover\'s dream in every slice.',
    price: 4200,
    category: 'banana-cake',
    emoji: '🌰',
    imageId: '1504387720438-88468770d0fc',
    gradientFrom: '#4A1800',
    gradientTo: '#8B4513',
    isAvailable: true,
  },
  {
    id: 'bc-cream-cheese',
    name: 'Cream Cheese Frosted Banana Cake',
    description: 'Smooth, tangy cream cheese frosting piled high over our signature banana cake. Heaven.',
    price: 5000,
    category: 'banana-cake',
    emoji: '🎂',
    imageId: '1601571503327-6cea83defcfe',
    gradientFrom: '#7C2D12',
    gradientTo: '#D4941A',
    tag: 'Premium',
    isAvailable: true,
  },
  {
    id: 'bc-caramel',
    name: 'Caramel Drizzle Banana Cake',
    description: 'Warm golden caramel cascades over moist banana layers. Sweet luxury in every bite.',
    price: 4500,
    category: 'banana-cake',
    emoji: '🍯',
    imageId: '1602483289282-f9c08b1f9992',
    gradientFrom: '#3D1208',
    gradientTo: '#C8741A',
    isAvailable: true,
  },
  {
    id: 'bc-mini',
    name: 'Mini Banana Cupcakes (6-pack)',
    description: 'Six bite-sized banana cupcakes — soft, sweet, and dangerously shareable. Or not.',
    price: 2500,
    category: 'banana-cake',
    emoji: '🧁',
    imageId: '1651378527289-36b9e2b8be58',
    gradientFrom: '#7C2D12',
    gradientTo: '#C27A1A',
    isAvailable: true,
  },

  // --- CROISSANTS ---
  {
    id: 'cr-butter',
    name: 'Classic Butter Croissant',
    description: 'Shatteringly crisp layers give way to pillowy, buttery warmth. Baked fresh every morning.',
    price: 800,
    category: 'croissant',
    emoji: '🥐',
    imageId: '1623334044303-241021148842',
    gradientFrom: '#5C1E00',
    gradientTo: '#C8741A',
    tag: 'Daily Fresh',
    isAvailable: true,
  },
  {
    id: 'cr-almond',
    name: 'Almond Croissant',
    description: 'Rich almond cream tucked inside a golden croissant, topped with flaked almonds and powdered sugar.',
    price: 1200,
    category: 'croissant',
    emoji: '✨',
    imageId: '1691480162735-9b91238080f6',
    gradientFrom: '#4A1800',
    gradientTo: '#9A6020',
    tag: 'Bestseller',
    isAvailable: true,
  },
  {
    id: 'cr-chocolate',
    name: 'Pain au Chocolat',
    description: 'Dark chocolate tucked inside layers of buttery pastry. Pure Parisian joy, every time.',
    price: 1000,
    category: 'croissant',
    emoji: '🍫',
    imageId: '1588195538326-c5b1e9f80a1b',
    gradientFrom: '#1A0800',
    gradientTo: '#451a03',
    isAvailable: true,
  },
  {
    id: 'cr-ham-cheese',
    name: 'Ham & Cheese Croissant',
    description: 'Premium smoked ham and melted cheese folded into a flaky, golden croissant. A savory dream.',
    price: 1500,
    category: 'croissant',
    emoji: '🧀',
    imageId: '1599940778173-e276d4acb2bb',
    gradientFrom: '#5C1E00',
    gradientTo: '#9A3412',
    isAvailable: true,
  },
  {
    id: 'cr-strawberry',
    name: 'Strawberry Jam Croissant',
    description: 'Sweet strawberry jam nestled in buttery flaky layers. Fresh, fruity, and absolutely delightful.',
    price: 950,
    category: 'croissant',
    emoji: '🍓',
    imageId: '1612366747681-e4ca6992b1e9',
    gradientFrom: '#6B1020',
    gradientTo: '#B01B38',
    isAvailable: true,
  },
  {
    id: 'cr-nutella',
    name: 'Nutella Croissant',
    description: 'Creamy Nutella swirled inside a warm, flaky croissant. The ultimate indulgence, no apologies.',
    price: 1100,
    category: 'croissant',
    emoji: '💛',
    imageId: '1530610476181-d83430b64dcd',
    gradientFrom: '#2D0E00',
    gradientTo: '#7C2D12',
    isAvailable: true,
  },

  // --- POPCORN ---
  {
    id: 'pc-classic',
    name: 'Classic Salted Popcorn',
    description: 'Light, airy, and perfectly seasoned with just the right touch of salt. The ideal snack for any occasion.',
    price: 500,
    category: 'popcorn',
    emoji: '🍿',
    imageId: '',
    gradientFrom: '#8B6914',
    gradientTo: '#F5D060',
    tag: 'New',
    isAvailable: true,
  },
  {
    id: 'pc-caramel',
    name: 'Caramel Popcorn',
    description: 'Golden caramel-coated kernels with a satisfying crunch. Sweet, buttery, and absolutely addictive.',
    price: 600,
    category: 'popcorn',
    emoji: '🍯',
    imageId: '',
    gradientFrom: '#6B3A0A',
    gradientTo: '#C4851C',
    isAvailable: true,
  },
  {
    id: 'pc-spicy',
    name: 'Spicy Pepper Popcorn',
    description: 'A bold kick of chilli and spice on every kernel. For those who like it fiery.',
    price: 550,
    category: 'popcorn',
    emoji: '🌶️',
    imageId: '',
    gradientFrom: '#7C1400',
    gradientTo: '#D4340A',
    isAvailable: true,
  },

  // --- BUNDLES ---
  {
    id: 'bn-morning',
    name: 'Morning Delight Bundle',
    description: '2 classic croissants + a generous slice of banana cake. Start your morning with pure joy.',
    price: 3500,
    category: 'bundle',
    emoji: '☀️',
    imageId: '1556742059-47b93231f536',
    gradientFrom: '#5C1E00',
    gradientTo: '#C27A1A',
    tag: 'Great Value',
    isAvailable: true,
  },
  {
    id: 'bn-family',
    name: 'Family Treat Bundle',
    description: 'Full banana cake + 6 freshly baked croissants. Feed the whole family in style.',
    price: 9000,
    category: 'bundle',
    emoji: '🥰',
    imageId: '1587241321921-91a834d6d191',
    gradientFrom: '#1A0800',
    gradientTo: '#7C2D12',
    tag: 'Family Fav',
    isAvailable: true,
  },
  {
    id: 'bn-office',
    name: 'Office Pack',
    description: '12 assorted croissants + a mini banana loaf. Make every team meeting unforgettable.',
    price: 12000,
    category: 'bundle',
    emoji: '🏆',
    imageId: '1608198093002-ad4e005484ec',
    gradientFrom: '#3D1208',
    gradientTo: '#9A3412',
    isAvailable: true,
  },
];

export const featuredProducts = products.filter(p =>
  ['bc-classic', 'cr-butter', 'cr-almond', 'bn-morning'].includes(p.id)
);

export const formatPrice = (price: number) =>
  new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', minimumFractionDigits: 0 }).format(price);
